struct ActorType {
    static let Undefined = 1
    static let TypeMask = 0x000000ff
    static let Mob = 0x00000100
    static let PathfinderMob = 0x00000200 | Mob
    static let Monster = 0x00000800 | PathfinderMob
    static let Animal = 0x00001000 | PathfinderMob
    static let TamableAnimal = 0x00004000 | Animal
    static let Ambient = 0x00008000 | Mob
    static let UndeadMob = 0x00010000 | Monster
    static let ZombieMonster = 0x00020000 | UndeadMob
    static let Arthropod = 0x00040000 | Monster
    static let Minecart = 0x00080000
    static let SkeletonMonster = 0x00100000 | UndeadMob
    static let EquineAnimal = 0x00200000 | TamableAnimal
    static let Projectile = 0x00400000
    static let AbstractArrow = 0x00800000
    static let WaterAnimal = 0x00002000 | PathfinderMob
    static let VillagerBase = 0x01000000 | PathfinderMob
    static let Chicken = 10 | Animal
    static let Cow = 11 | Animal
    static let Pig = 12 | Animal
    static let Sheep = 13 | Animal
    static let Wolf = 14 | TamableAnimal
    static let Villager = 15 | VillagerBase
    static let MushroomCow = 16 | Animal
    static let Squid = 17 | WaterAnimal
    static let Rabbit = 18 | Animal
    static let Bat = 19 | Ambient
    static let IronGolem = 20 | PathfinderMob
    static let SnowGolem = 21 | PathfinderMob
    static let Ocelot = 22 | TamableAnimal
    static let Horse = 23 | EquineAnimal
    static let PolarBear = 28 | Animal
    static let Llama = 29 | Animal
    static let Parrot = 30 | TamableAnimal
    static let Dolphin = 31 | WaterAnimal
    static let Donkey = 24 | EquineAnimal
    static let Mule = 25 | EquineAnimal
    static let SkeletonHorse = 26 | EquineAnimal | UndeadMob
    static let ZombieHorse = 27 | EquineAnimal | UndeadMob
    static let Zombie = 32 | ZombieMonster
    static let Creeper = 33 | Monster
    static let Skeleton = 34 | SkeletonMonster
    static let Spider = 35 | Arthropod
    static let PigZombie = 36 | UndeadMob
    static let Slime = 37 | Monster
    static let EnderMan = 38 | Monster
    static let Silverfish = 39 | Arthropod
    static let CaveSpider = 40 | Arthropod
    static let Ghast = 41 | Monster
    static let LavaSlime = 42 | Monster
    static let Blaze = 43 | Monster
    static let ZombieVillager = 44 | ZombieMonster
    static let Witch = 45 | Monster
    static let Stray = 46 | SkeletonMonster
    static let Husk = 47 | ZombieMonster
    static let WitherSkeleton = 48 | SkeletonMonster
    static let Guardian = 49 | Monster
    static let ElderGuardian = 50 | Monster
    static let Npc = 51 | Mob
    static let WitherBoss = 52 | UndeadMob
    static let Dragon = 53 | Monster
    static let Shulker = 54 | Monster
    static let Endermite = 55 | Arthropod
    static let Agent = 56 | Mob
    static let Vindicator = 57 | Monster
    static let Phantom = 58 | UndeadMob
    static let IllagerBeast = 59 | Monster
    static let ArmorStand = 61 | Mob
    static let TripodCamera = 62 | Mob
    static let Player = 63 | Mob
    static let ItemEntity = 64
    static let PrimedTnt = 65
    static let FallingBlock = 66
    static let MovingBlock = 67
    static let ExperiencePotion = 68 | Projectile
    static let Experience = 69
    static let EyeOfEnder = 70
    static let EnderCrystal = 71
    static let FireworksRocket = 72
    static let Trident = 73 | Projectile | AbstractArrow
    static let Turtle = 74 | Animal
    static let Cat = 75 | TamableAnimal
    static let ShulkerBullet = 76 | Projectile
    static let FishingHook = 77
    static let Chalkboard = 78
    static let DragonFireball = 79 | Projectile
    static let Arrow = 80 | Projectile | AbstractArrow
    static let Snowball = 81 | Projectile
    static let ThrownEgg = 82 | Projectile
    static let Painting = 83
    static let LargeFireball = 85 | Projectile
    static let ThrownPotion = 86 | Projectile
    static let Enderpearl = 87 | Projectile
    static let LeashKnot = 88
    static let WitherSkull = 89 | Projectile
    static let BoatRideable = 90
    static let WitherSkullDangerous = 91 | Projectile
    static let LightningBolt = 93
    static let SmallFireball = 94 | Projectile
    static let AreaEffectCloud = 95
    static let LingeringPotion = 101 | Projectile
    static let LlamaSpit = 102 | Projectile
    static let EvocationFang = 103 | Projectile
    static let EvocationIllager = 104 | Monster
    static let Vex = 105 | Monster
    static let MinecartRideable = 84 | Minecart
    static let MinecartHopper = 96 | Minecart
    static let MinecartTNT = 97 | Minecart
    static let MinecartChest = 98 | Minecart
    static let MinecartFurnace = 99 | Minecart
    static let MinecartCommandBlock = 100 | Minecart
    static let IceBomb = 106 | Projectile
    static let Balloon = 107
    static let Pufferfish = 108 | WaterAnimal
    static let Salmon = 109 | WaterAnimal
    static let Drowned = 110 | ZombieMonster
    static let Tropicalfish = 111 | WaterAnimal
    static let Fish = 112 | WaterAnimal
    static let Panda = 113 | Animal
    static let Pillager = 114 | Monster
    static let VillagerV2 = 115 | VillagerBase
    static let ZombieVillagerV2 = 116 | ZombieMonster
    static let Shield = 117
    static let WanderingTrader = 118 | PathfinderMob
    static let Lectern = 119
    static let ElderGuardianGhost = 120 | Monster
    static let Fox = 121 | Animal
    static let Bee = 122 | Mob
    static let Piglin = 123 | Mob
    static let Hoglin = 124 | Animal
    static let Strider = 125 | Animal
    static let Zoglin = 126 | UndeadMob
    static let PiglinBrute = 127 | Mob
    static let Goat = 128 | Animal
    static let GlowSquid = 129 | WaterAnimal
    static let Axolotl = 130 | Animal
    static let Warden = 131 | Monster
    static let Frog = 132 | Animal
    static let Tadpole = 133 | WaterAnimal
    static let Allay = 134 | Mob
    static let ChestBoatRideable = 136 | BoatRideable
    static let TraderLlama = 137 | Llama
    static let Camel = 138 | Animal
    static let Sniffer = 139 | Animal
    static let Breeze = 140 | Monster
    static let BreezeWindChargeProjectile = 141 | Projectile
    static let Armadillo = 142 | Animal
    static let WindChargeProjectile = 143 | Projectile
    static let Bogged = 144 | SkeletonMonster
    static let OminousItemSpawner = 145
    static let Creaking = 146 | Monster
    static let HappyGhast = 147 | Animal
}